create table if not exists public.app_settings (
  id integer primary key default 1 check (id = 1),
  default_late_grace integer not null default 15 check (default_late_grace >= 0),
  default_early_grace integer not null default 5 check (default_early_grace >= 0),
  updated_at timestamptz not null default now()
);
insert into public.app_settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.employee_policies (
  id bigint generated by default as identity primary key,
  employee_name text not null unique,
  shift_mode text not null default 'single',
  shift_one text not null default 'morning',
  shift_two text not null default 'evening',
  rotation_start date not null default current_date,
  updated_at timestamptz not null default now()
);
alter table public.employee_policies add column if not exists shift_mode text not null default 'single';
alter table public.employee_policies add column if not exists shift_one text not null default 'morning';
alter table public.employee_policies add column if not exists shift_two text not null default 'evening';
alter table public.employee_policies add column if not exists rotation_start date not null default current_date;

create table if not exists public.attendances (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  work_date date not null,
  check_in time null,
  check_out time null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(employee_name, work_date)
);
alter table public.app_settings enable row level security;
alter table public.employee_policies enable row level security;
alter table public.attendances enable row level security;
do $$ begin create policy "public app settings" on public.app_settings for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public employee policies" on public.employee_policies for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public read attendance" on public.attendances for select using (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public insert attendance" on public.attendances for insert with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "public update attendance" on public.attendances for update using (true) with check (true); exception when duplicate_object then null; end $$;
